apiVersion: v1
kind: Namespace
metadata:
  name: redpanda
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  clusterSpec:
    image:
      repository: docker.redpanda.com/redpandadata/redpanda
      tag: v26.1.7
    statefulset:
      replicas: 3
      nodeSelector:
        role: redpanda
    resources:
      cpu:
        cores: 1
      memory:
        container:
          max: 2Gi
          min: 2Gi
    storage:
      persistentVolume:
        enabled: true
        size: 20Gi
        storageClass: csi-driver-lvm-striped-xfs
    external:
      enabled: true
      type: LoadBalancer
      addresses:
        - ab14f1341b5a04455951a4c439736dab-638340892.eu-west-1.elb.amazonaws.com
        - ac89516824be94ebd9a1cd2b16ed6b92-1451718857.eu-west-1.elb.amazonaws.com
        - aa2598d94380b48f6b6c4619e7a40926-1282810100.eu-west-1.elb.amazonaws.com
    listeners:
      kafka:
        port: 9092
        authenticationMethod: none
        external: {}
      http:
        port: 8082
        enabled: true
        authenticationMethod: none
        external: {}
      admin:
        port: 9644
        external: {}
      rpc:
        port: 33145
    logging:
      logLevel: info
      usageStats:
        enabled: false
    monitoring:
      enabled: true
      scrapeInterval: 15s
      labels:
        release: kube-prometheus-stack
    console:
      enabled: false
